"""Initial

Revision ID: 11a23b21ac64
Revises: 
Create Date: 2025-06-03 21:36:04.191408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a23b21ac64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bg_tasks',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failure', name='bgtaskstatus'), nullable=False),
    sa.Column('result_msg', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('models',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('logistic_regression', 'multinomial_nb', 'linear_svc', name='mlmodeltype'), nullable=False),
    sa.Column('is_dl_model', sa.Boolean(), nullable=False),
    sa.Column('is_trained', sa.Boolean(), nullable=False),
    sa.Column('is_loaded', sa.Boolean(), nullable=False),
    sa.Column('model_params', sa.JSON(), nullable=False),
    sa.Column('vectorizer_params', sa.JSON(), nullable=False),
    sa.Column('saved_model_file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_table('models')
    op.drop_table('bg_tasks')
    # ### end Alembic commands ###
